# Generated by Django 3.1.2 on 2020-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='products', max_length=100)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
    ]
