# Generated by Django 3.1.2 on 2020-10-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hk', '0002_assets_categories_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('woo_id', models.CharField(default='', max_length=100)),
                ('mongo_id', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
