# Generated by Django 3.1.2 on 2020-10-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hk', '0003_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('woo_id', models.CharField(default='', max_length=100)),
                ('mongo_id', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('avatar', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
